apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
      - name: order-management
        image: order-management-service:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: order-management-service
spec:
  selector:
    app: order-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
